full_rebuild: true
name: "2010 Bible Study on Matthew in Church in HK"
description: "A 2010 Bible Study Group on Matthew in Church in Hong Kong"
domain: churchinhk.github.io #If you want to force HTTPS, put down the domain without the http: e.g. example.com
url: https://churchinhk.github.io #place url
baseurl: /bible-study-on-matthew #place folder name if site is served in subfolder
permalink: /:title.html
author: #For jekyll-feed
  name: "Kolen"
  email: christian.kolen@gmail.com
  uri: https://ickc.github.io/about/

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

gems:
  - jekyll-sitemap

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, p, rt, rp, optgroup, option, caption]
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]